In [1]:
import progtv
from datetime import datetime
from pathlib import Path
import pandas as pd

/home/david/miniconda3/envs/progtv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-02-24 22:50:08.253224: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-02-24 22:50:08.268032: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-02-24 22:50:08.272662: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-24 22:50:08.284601: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
tv_program = progtv.TVProgram()
current_directory = Path.cwd()
file_name_rated = f"{current_directory}/{tv_program.download_folder}/progtv_rated_{datetime.now().today().strftime('%Y-%m-%d')}.pkl"
rated_progs = tv_program.read_programs(file_name_rated)

In [3]:
rated_progs

,id,name,icon,programs
0,TF1.fr,TF1,https://www.teleboy.ch/assets/stations/308/ico...,...
1,France2.fr,France 2,https://www.teleboy.ch/assets/stations/342/ico...,name ...
2,France3.fr,France 3,https://www.teleboy.ch/assets/stations/58/icon...,n...
3,CanalPlus.fr,Canal+,https://focus.telerama.fr/500x500/0000/00/01/c...,name ...
4,France5.fr,France 5,https://www.teleboy.ch/assets/stations/80/icon...,...
5,M6.fr,M6,https://www.teleboy.ch/assets/stations/312/ico...,name ...
6,Arte.fr,Arte,https://www.teleboy.ch/assets/stations/330/ico...,name ...
7,C8.fr,C8,https://focus.telerama.fr/500x500/0000/00/01/c...,name ...
8,W9.fr,W9,https://www.teleboy.ch/assets/stations/268/ico...,name ...
9,TMC.fr,TMC,https://www.teleboy.ch/assets/stations/383/ico...,name ...
10,NT1.fr,TFX,https://focus.telerama.fr/500x500/0000/00/01/c...,name ...
11,NRJ12.fr,NRJ12,https://www.teleboy.ch/assets/stations/374/ico...,name start...
12,LaChaineParlementaire.fr,LCP,https://focus.telerama.fr/500x500/0000/00/01/c...,name ...
13,France4.fr,France 4,https://www.teleboy.ch/assets/stations/288/ico...,name star...
17,Gulli.fr,Gulli,https://www.teleboy.ch/assets/stations/270/ico...,...
18,TF1SeriesFilms.fr,TF1 Séries-Films,https://www.teleboy.ch/assets/stations/372/ico...,...
19,LEquipe21.fr,La chaine l’Équipe,https://www.teleboy.ch/assets/stations/373/ico...,name ...
20,6ter.fr,6ter,https://www.teleboy.ch/assets/stations/367/ico...,name start...
21,Numero23.fr,RMC STORY,https://www.teleboy.ch/assets/stations/376/ico...,name ...
22,RMCDecouverte.fr,RMC Découverte,https://www.teleboy.ch/assets/stations/380/ico...,...
23,Cherie25.fr,Chérie 25,https://www.teleboy.ch/assets/stations/371/ico...,name ...
26,ParisPremiere.fr,Paris Première,https://focus.telerama.fr/500x500/0000/00/01/c...,n...

In [5]:
rated_progs.iloc[0]["programs"].sort_values(by="start")

,name,start,end,channel,icon,rating,cat,desc,embeddings_camembert,cat_encoded,rating_encoded,note_pred
0,Programmes de la nuit,2025-02-23 02:35:00,2025-02-23 06:00:00,TF1.fr,https://img.bouygtel.fr/CMS/images/16467FF15CA...,Tout public,Programme,"A suivre, des rediffusions des émissions de la...","[[0.051920388, 0.059774883, 0.029275244, 0.058...",13,2,0.053465
1,TFou,2025-02-23 06:00:00,2025-02-23 10:05:00,TF1.fr,https://img.bouygtel.fr/CMS/images/59698756F46...,Tout public,Magazine,Molang / Les Pyjamasquess Power Heroes Le cerc...,"[[0.00015642107, 0.078512095, -0.04042699, 0.1...",9,2,0.040370
2,Automoto,2025-02-23 10:05:00,2025-02-23 11:00:00,TF1.fr,https://img.bouygtel.fr/CMS/images/EAEC09ED5FD...,Tout public,Sport,Le rendez-vous hebdomadaire des passionnés d'a...,"[[0.040437136, -0.045361366, 0.11239266, 0.101...",16,2,0.077269
3,Téléfoot,2025-02-23 11:00:00,2025-02-23 11:50:00,TF1.fr,https://img.bouygtel.fr/CMS/images/583ADB3DBC0...,Tout public,Sport,"Dans la première partie de l'émission, les der...","[[0.040291883, -0.044099208, -0.016136935, 0.1...",16,2,0.087266
4,Les douze coups de midi,2025-02-23 11:50:00,2025-02-23 12:50:00,TF1.fr,https://img.bouygtel.fr/CMS/images/3004E579827...,Tout public,Divertissement,"Emission du 23 février 2025 - Chaque jour, qua...","[[0.033727765, -0.091035955, 0.017671388, 0.10...",3,2,0.096118
...,...,...,...,...,...,...,...,...,...,...,...,...
207,Le fil d'Ariane (Ariane à la fête foraine) S1 ...,2025-03-03 21:10:00,2025-03-03 22:00:00,TF1.fr,https://images.voomotion.be/Events/2025/02/15/...,NaN,Série Comédie,«Ariane à la fête foraine»Malgré le succès de ...,"[[0.0633023, 0.043428227, 0.06323861, 0.074869...",18,3,0.072373
208,Le fil d'Ariane (Ariane à la fête foraine) S1 ...,2025-03-03 22:00:00,2025-03-03 22:55:00,TF1.fr,https://images.voomotion.be/Events/2025/02/15/...,NaN,Série Comédie,«Ariane à la fête foraine»Ariane doit explorer...,"[[0.06851768, -0.04099093, -0.040374234, 0.115...",18,3,0.071665
209,Eurodreams,2025-03-03 22:55:00,2025-03-03 23:00:00,TF1.fr,https://images.voomotion.be/Events/2024/12/23/...,NaN,Magazine,"Tous les lundis et jeudis après le prime-time,...","[[0.040339306, -0.1992287, -0.028395569, 0.075...",9,3,0.077515
210,New York Unité Spéciale (Le devoir d'espérer) ...,2025-03-03 23:00:00,2025-03-03 23:50:00,TF1.fr,https://images.voomotion.be/Events/2025/02/15/...,NaN,Série Policière,«Le devoir d'espérer»L'USV traque un agresseur...,"[[-0.013532457, -0.13462208, 0.0879387, 0.1424...",20,3,0.070731
211,New York Unité Spéciale (La victime imparfaite...,2025-03-03 23:50:00,2025-03-04 00:40:00,TF1.fr,https://images.voomotion.be/Events/2023/04/08/...,NaN,Série Policière,«La victime imparfaite»L'équipe se lance à la ...,"[[0.03763156, -0.0879226, 0.053605527, 0.10576...",20,3,0.063692

In [ ]:
def get_best_programs(rated_progs, n=5, whitelist=None):
    best_progs = pd.DataFrame()
    best_progs_whitelist = pd.DataFrame()
    for i, row in rated_progs.iterrows():
        best_prog = row.programs[row.programs["start"] > datetime.now()]
        best_prog = best_prog.nlargest(n, "note_pred")
        # Calculate the duration of each program
        best_prog.loc[:, "duration"] = (best_prog["end"] - best_prog["start"]).dt.total_seconds() / 60
        # add channel name and icon
        try:
            best_prog.loc[:, "channel_name"] = row["name"]
            best_prog.loc[:, "channel_icon"] = row["icon"]
        except:
                pass
        best_progs = pd.concat([best_progs, best_prog])
        # drop duplicates programs
        best_progs = best_progs.drop_duplicates(subset=["name"])
        for channel in whitelist:
            best_prog_whitelist = best_progs[best_progs["channel_name"] == channel].nlargest(1, "note_pred")
            best_progs_whitelist = pd.concat([best_progs_whitelist, best_prog_whitelist])
        best_progs = best_progs.nlargest(n, "note_pred")
        best_progs = pd.concat([best_progs, best_progs_whitelist])
        best_progs = best_progs.drop_duplicates(subset=["name"])
    return best_progs

In [7]:
get_best_programs(rated_progs, n=5, whitelist=["TF1", "France 2", "France 3", "Canal+"])

,name,start,end,channel,icon,rating,cat,desc,embeddings_camembert,cat_encoded,rating_encoded,note_pred,duration,channel_name,channel_icon
93,J'irai dormir chez vous,2025-02-28 21:10:00,2025-02-28 23:00:00,RMCDecouverte.fr,https://img.bouygtel.fr/CMS/images/9CFA11B08A8...,Tout public,Aucun genre,Le plus célèbre des globetrotters prend cette ...,"[[0.0017619004, 0.02942601, 0.008365242, 0.104...",0,2,0.548742,110.0,RMC Découverte,https://www.teleboy.ch/assets/stations/380/ico...
126,Pêche XXL,2025-03-02 17:55:00,2025-03-02 18:55:00,RMCDecouverte.fr,https://img.bouygtel.fr/CMS/images/0C0291C6347...,Tout public,Aucun genre,"Un poisson connu pour sa force démesurée, capa...","[[0.03691365, -0.034912325, -0.045708235, 0.10...",0,2,0.501334,60.0,RMC Découverte,https://www.teleboy.ch/assets/stations/380/ico...
5,Très très bon,2025-02-23 11:25:00,2025-02-23 12:00:00,ParisPremiere.fr,https://img.bouygtel.fr/CMS/images/13C61DA6925...,Tout public,Art de vivre,"Tables bistronomiques, adresses traditionnelle...","[[0.041976355, 0.14343691, 0.023603069, 0.0717...",1,3,0.481715,35.0,Paris Première,https://focus.telerama.fr/500x500/0000/00/01/c...
29,Les secrets du Saint Graal,2025-02-24 23:25:00,2025-02-25 00:40:00,Numero23.fr,https://img.bouygtel.fr/CMS/images/DAB97C47E98...,Tout public,Aucun genre,"De tous temps, le Graal a toujours fasciné. Ob...","[[0.029200992, 0.07307897, -0.09516419, 0.1077...",0,1,0.472152,75.0,RMC STORY,https://www.teleboy.ch/assets/stations/376/ico...
28,L'énigme du Saint Graal : mythe ou réalité ?,2025-02-24 22:15:00,2025-02-24 23:25:00,Numero23.fr,https://img.bouygtel.fr/CMS/images/778E6CF32FD...,Tout public,Aucun genre,"De tous temps, le Graal a toujours fasciné. Ob...","[[0.02870309, 0.07339719, -0.10025054, 0.10739...",0,1,0.458952,70.0,RMC STORY,https://www.teleboy.ch/assets/stations/376/ico...
37,Prise au piège dans ma maison,2025-02-24 15:50:00,2025-02-24 17:35:00,TF1.fr,https://img.bouygtel.fr/CMS/images/D6AF6B00B10...,-10,Action,"Kyle Hastings, créateur d'un projet technologi...","[[0.012755152, -0.06555776, -0.012353742, 0.13...",0,0,0.434674,105.0,TF1,https://www.teleboy.ch/assets/stations/308/ico...
33,Flair de famille,2025-02-24 00:26:00,2025-02-24 01:50:00,France2.fr,https://img.bouygtel.fr/CMS/images/BB2DFDBB163...,Tout public,Aucun genre,"Quand le corps de Jackie Lefranc, ex ""Reine de...","[[0.033027608, 0.012889833, 0.004484705, 0.149...",1,1,0.408821,84.0,France 2,https://www.teleboy.ch/assets/stations/342/ico...
36,Les carnets de Julie,2025-02-23 15:40:00,2025-02-23 16:40:00,France3.fr,https://img.bouygtel.fr/CMS/images/61D9C4AA6B5...,Tout public,Art de vivre,"Au sommaire : ""La pintade à la catalane"". - ""T...","[[0.049043663, 0.01212829, -0.04833677, 0.0727...",0,1,0.404522,60.0,France 3,https://www.teleboy.ch/assets/stations/58/icon...
23,Le Successeur,2025-02-24 01:11:00,2025-02-24 03:00:00,CanalPlus.fr,https://img.bouygtel.fr/CMS/images/F48B0394B48...,-10,Action,Tout juste promu directeur artistique d'une ma...,"[[0.01249852, -0.063608825, 0.016820846, 0.125...",0,0,0.453401,109.0,Canal+,https://focus.telerama.fr/500x500/0000/00/01/c...